### ISSUE TITLE
Support the distributed architectures

### ISSUE THREAD

**Issue by tokarenko** [artisanofcode/python-banshee#102]
## Description
I suggest to support messaging in distributed architectures.

## Context
I had to introduce distribution into my, originally monolithic, software architecture. And I would like to to continue using the Banshee to communicate with the distributed parts.

## Possible implementation
I would like to avoid introduction and support of additional distributed message queue. For the minimalistic use cases I suggest to consider PostgreSQL database as distribution engine: as [described](https://worlds-slowest.dev/posts/postgresql-message-queue/) here and implemented in [pg_mq](https://github.com/perfectsquircle/pg_mq).

**Comment by danielknell** [comment]
This is a duplciate of #1 which will provide a concept of "channels" to send messages to external worker processes.

Postgres will likely be one of the first channels implemented, as I use it in production projects using banshee myself, and reusing the existing database for messaging will simplify development environments.

Unfortunatly when I decided to not dictate how users define their commands/events/queries/contexts, I shot myself in the foot and made this piece far more complicated than it otherwise could have been. It requires being able to serialise the complex types that can be used in messages and contexts in a way that can be meaningfully sent across different message queue implementations.
